### PR TITLE
ignore zero area contours only when pyclipper cannot add them

### PR DESCRIPTION
**Pull request by typemytype**
this solves zero area self intersection paths, but still ignores reall zero area paths like lines

#50
#48

### CODE REVIEW

**Comment by typemytype** [comment]
test fails cause difference and xor are NOT working properly (testing now)

**Comment by typemytype** [comment]
all fixed now
all test cases are working now
 @anthrotype could you review and merge, this is maybe a change that can have a new release

**Comment by typemytype** [comment]
I dont now what adding a check for bounds does for performance... but since the last version of pyclipper this raises an error. Previous versions simple ignores empty clipper paths.

**Comment by typemytype** [comment]
a quick performance test: https://gist.github.com/typemytype/4ad64ad5d4f72b6662d74f418cd67c44

the timeit result are to close to each other (they both win once in a while) to speak of a performance dip.

**Comment by anthrotype** [comment]
Thanks @typemytype

**Pull request merged**
