### PR TITLE
Remove binary module

### PR DESCRIPTION
**Pull request by khaledhosny**
This is a Mac-only, it should be built for each platform from the
cppWrapper directory.

### CODE REVIEW

**Comment by typemytype** [comment]
True,
could you add a build script to the setup.py so the .so will be build on install?

thanks

**Comment by khaledhosny** [comment]
The `cppWrapper` directly seems to be a standalone module with its own setup.py file, may be we should just fold it into the main module?

**Comment by typemytype** [comment]
I don't know, this requires that every one who want to use this packages has to install cython. 

Is it an idea to add different setup.py files for different OSs? similarly as AFDKO?

**Comment by anthrotype** [comment]
you can simply build pre-compiled Python wheels for each platform so people won't need to install Cython. Even better, you can setup Travis and Appveyor CI to automatically build the wheels for you and deploy them directly to Github Releases and PyPI.
I could help with the setup.py if you need.

**Comment by typemytype** [comment]
> I could help with the setup.py if you need.
> 
> 
oh, yeah help :)


gr Frederik
www.typemytype.com

**Comment by anthrotype** [comment]
OK, like Khaled said, I shall fold the standalone `cppWrapper` in the main module and have a single setup.py build the extension module.

**Comment by anthrotype** [comment]
the *.so file has been removed, this can be closed now.

**Pull request closed without merging**
