### PR TITLE
Sort contours after executing on them

### PR DESCRIPTION
**Pull request by madig**
Tackle #55.

This sorts contours by their point closest to origin. The downside here is that this is yet again a breaking change 😢 Are there better methods? If at least a subset of starting points is guaranteed to stay where they are, the contour order could be "transplanted", but I'm not familiar enough with the code/algorithm to judge this.

If the way forward is decided, I will take care of the tests.

### CODE REVIEW

**Comment by belluzj** [comment]
Could you manage to reverse-engineer the order that pyclipper was applying on most of the glyphs (i.e. all those that didn't change between platforms)? That way the change is only "breaking" for those particular glyphs that were unstable between platforms anyway

**Comment by madig** [comment]
Jany and me couldn't make out an obvious pattern. We looked at Source Code Pro Black git master.

**Comment by madig** [comment]
It is indeed a hack. I am too weak to dive into pyclipper 😥

The order matters because TrueType hinting. We found this while building a font on Linux with VTT hints done on the same font compiled on Windows.

Oh well. I suppose I can implement this internally somehow.

**Comment by typemytype** [comment]
I understand the problem

but its not good to change everything else to fix it on windows...

did you report a bug on polyclipper yet?
https://sourceforge.net/p/polyclipping/bugs/

**Comment by anthrotype** [comment]
> https://sourceforge.net/p/polyclipping/bugs/

ah, we didn't know that was the new upstream repository. I was looking at the old link and thought it was now unmaintained.

@madig it may be worth raising the bug over there

**Comment by madig** [comment]
Optional ufo2ft filter implemented in https://github.com/googlefonts/ufo2ft/pull/345.

**Pull request closed without merging**
