### PR TITLE
Raise BooleanOperationsError on open contour

### PR DESCRIPTION
**Pull request by moyogo**
Allow users to better report error when this occurs.

### CODE REVIEW

**Comment by moyogo** [comment]
Specifically for https://github.com/googlei18n/fontmake/blob/6cdf44ea38d17f9bb14fa65c1c9bc6ea82e3b89b/Lib/fontmake/font_project.py#L110

**Comment by anthrotype** [comment]
for reference, also see https://github.com/googlei18n/fontmake/issues/354

Maybe you could define a subclass of BooleanOperationsError that's raised in this specific case when an input contour is open?

like these:
https://github.com/typemytype/booleanOperations/blob/master/Lib/booleanOperations/exceptions.py

**Comment by moyogo** [comment]
@anthrotype OpenContourError?

**Comment by anthrotype** [comment]
Yeah

**Comment by typemytype** [comment]
+1 for `OpenContourError` and a separate error when this occurs instead of raise

**Comment by moyogo** [comment]
OK, it raises OpenContourError now.
I guess we can have an option not to raise when we support open paths (see #44).

**Pull request merged**
