### PR TITLE
make setup.py build extension module from source

### PR DESCRIPTION
**Pull request by anthrotype**
I made a single `setup.py` script which compiles and installs both the pure Python package and the Cython C++ wrapper.

Hence, I removed the platform-specific `pyClipper.so` file from the git tree.

This means, Cython is required to build the extension module from a cloned Github repository.

However, I also made sure that the source distributions (e.g. `.tar.gz` or `.zip`) will include the Cython-generated `.cpp` source files, so that users downloading them will not need to install Cython (that is also what the Cython documentation recommends in these cases).

The presence of an empty `dev` file will signal to setup.py whether one is in "development" mode or "distribution" mode; only the former requires Cython (I added a note at the end of the README.md file explaining this).

If you're worried that OS X users, who so far would use the precompiled `*.so` module, will not be able to install booleanOperations without a C++ compiler, then you can do the following.

Make a new "Github Release" and upload any pre-compiled Python wheels in there. You can use the command `pip wheel -v .` to create a wheel package, from root of the project. First you need to install the `wheel` package, as usual via `pip install wheel`.

I would also recommend to upload the source distribution on the same Github Release (i.e. `python setup.py sdist --formats=gztar,zip`), for those systems which don't use wheels but can compile directly from source.

Users will then be able to install booleanOperations with the following pip command: 

    pip install --find-links https://github.com/typemytype/booleanOperations/releases/latest booleanOperations

Pip will select the appropriate wheel for the target platform if it's available, or will try to build one from the source distribution.

I will send separate pull requests for setting up continuous integration (CI) services like Travis and Appveyor, so that we can use them to automatically build the wheels, and send them to Github upon tagging a new release.

Let me know if that is ok,
thanks.

Cosimo

### CODE REVIEW

**Comment by anthrotype** [comment]
@typemytype sorry, did you have a chance to review this?
I cannot set up the CI servers without this patch being merged first.
Thanks.

**Comment by typemytype** [comment]
Tomorrow...

gr
Frederik
www.typemytype.com

**Comment by typemytype** [comment]
merged, is there anything I have todo to make this work?

thanks!

**Comment by anthrotype** [comment]
thanks!
Yes, you should tag a release and upload to GitHub the source distribution and the compiled wheels.

To make the .tar.gz and .zip source distributions:
```bash
python setup.py sdist --formats=gztar,zip
```

to make the compiled wheels (built for the python version and platform of the python interpreter used to produce them):
```
# better updating these first, just in case
pip install --upgrade wheel setuptools pip
# then from the root of booleanOperations git repo
pip wheel -v -w dist .
```
You'll find both the compiled wheel and the source distributions in the `dist/` subfolder.

After you have uploaded the files to Github Releases, then you need to update the README so instruct the users on how to install the package.

This pip command will do the job for you:

```
pip install --find-links https://github.com/typemytype/booleanOperations/releases/latest booleanOperations
```

Let me know if you have any questions.

**Comment by typemytype** [comment]
I really want to get this to work and I try hard to understand, but could you remind me why this is necessary? This makes a simple thing really complicated?? 

The compiled pyClipper.so is nowhere to be found... where did that go? it should be in the lib folder. But after a setup.py it is not there. I also cannot find this compiled file in the zipped files.

My gut feeling now is "revert-as-soon-as-possible"!

**Comment by anthrotype** [comment]
normally, you don't ship platform dependent compiled binaries (like the *.so file) in your source distribution, and similarly you don't store them in the git repository.

That's why I and Khaled removed it.

The tar.gz or zip source distribution only contains the python and cpp source files (and don't require cython to build the extension).

The wheel packages do contain the compiled extension module. You can rename a wheel (it's simply a zip package) and inspect its content. You'll see the pyClipper.so will be there.

You install a wheel package via `pip install -v package.whl` (-v is for verbose).

There's nothing to be concerned about.

**Comment by anthrotype** [comment]
if you want to make user's life even simpler, instead of asking them to download the wheel from the Github releases, you could register booleanOperations on the Python Package Index (PyPI) so that one could install it by simply doing `pip install booleanOperations`.

I suggested the github releases method because I thought it would be simpler for you (make a tag, upload the archives, write some release notes, done). I've never uploaded a package to PyPI myself, but it should be straightforward.

**Comment by typemytype** [comment]
to continue this discussion:

Im not convinced about the update / auto building thing. It adds lots of folders and files I don't need, and I don't what to keep updating them. Making it still very complicated, see Reads issue.

Still thinking about reverting it back to the simple repo as it was before. 
All those changes did improve the package and I lost more then 2 days already. I prefer to spend my time on more important things. The only downside you mentioned was that binary files aren't supposed to be in the repo, well that part is not my code, and it has to be compiled only once in a lifetime, and it precompiled for OSx. If others already succeeded to install linux or windows, Im sure they can handle to compile on their local machines...

**Comment by anthrotype** [comment]
Of course, your are free to revert the changes.

> Making it still very complicated

I contend it's actually easier than it was before. With a single `python setup.py install` from the cloned repo, one can now compile the extension and install the package in one go.

> see Reads issue

Read didn't explain what errors he incurred while building the module. The [Travis](https://travis-ci.org/anthrotype/booleanOperations/builds/89759850) and [Appveyor](https://ci.appveyor.com/project/anthrotype/booleanoperations/build/1.0.3) build logs demonstrate that it compiles just fine, provided one has the right toolchain.

Besides I didn't make any changes to the .cpp sources. I only merged the two setup.py scripts into one, and added the ability to create source distributions that don't require Cython to build.

>  It adds lots of folders and files I don't need, and I don't what to keep updating them

The additional files and folders contain the data and scripts required to set up the continuous integration services. At the moment, booleanOperations doesn't contain any automated tests, therefore the CI can only run the build and deploy the compiled artifacts. But once (or if) you start adding a test suite, you will understand how convenient CI are to help you ensure the quality and maintainability of the code.

> All those changes did improve the package

I guess you meant the "changes *didn't* improve" the package. I don't understand how you have "lost 2 days already".

> that part is not my code, and it has to be compiled only once

Well, no code is ever perfect or set in stone.
Anyway, as you have admitted yourself, you only care about OS X users.
I am sure others can handle to compile successfully on different operating systems.

**Comment by davelab6** [comment]
I would like to see this unit tested so it can be updated from time to time to use the latest Clipper library releases without regressions, and this pr seems like a prerequisite for that. 

@typemytype I understand if you don't want to maintain stuff you don't care to understand, but I suggest to file and  assign all such issues to cosimo :)

**Pull request merged**
